### ISSUE TITLE
Failure building in linux

### ISSUE THREAD

**Issue by dkowis** [cucumber-attic/bool#37]
Travis isn't failing so there must be something I'm failing to build or whatever, but I'm not sure what it could be, wasn't happening in 1.9.3 :(

```
cd tmp/x86-mingw32/bool_ext/2.0.0
/home/dkowis/.rvm/rubies/ruby-2.0.0-p0/bin/ruby -I. -rfake ../../../../ext/bool_ext/extconf.rb
/home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require': cannot load such file -- win32/resolv (LoadError)
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/resolv.rb:169:in `<class:Hosts>'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/resolv.rb:167:in `<class:Resolv>'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/2.0.0/resolv.rb:37:in `<top (required)>'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/remote_fetcher.rb:4:in `<top (required)>'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/spec_fetcher.rb:1:in `<top (required)>'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /home/dkowis/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.0.pre.7/lib/bundler/source/rubygems.rb:3:in `<top (required)>'
    from /home/dkowis/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.0.pre.7/lib/bundler/dsl.rb:18:in `initialize'
    from /home/dkowis/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.0.pre.7/lib/bundler/dsl.rb:8:in `new'
    from /home/dkowis/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.0.pre.7/lib/bundler/dsl.rb:8:in `evaluate'
    from /home/dkowis/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.0.pre.7/lib/bundler/definition.rb:19:in `build'
    from /home/dkowis/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.0.pre.7/lib/bundler.rb:145:in `definition'
    from /home/dkowis/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.0.pre.7/lib/bundler.rb:113:in `setup'
    from /home/dkowis/.rvm/gems/ruby-2.0.0-p0/gems/bundler-1.3.0.pre.7/lib/bundler/setup.rb:7:in `<top (required)>'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
    from /home/dkowis/.rvm/rubies/ruby-2.0.0-p0/lib/ruby/site_ruby/2.0.0/rubygems/core_ext/kernel_require.rb:45:in `require'
rake aborted!
Command failed with status (1): [/home/dkowis/.rvm/rubies/ruby-2.0.0-p0/bin...]
/home/dkowis/.rvm/gems/ruby-2.0.0-p0/gems/rake-compiler-0.8.3/lib/rake/extensiontask.rb:153:in `block (2 levels) in define_compile_tasks'
/home/dkowis/.rvm/gems/ruby-2.0.0-p0/gems/rake-compiler-0.8.3/lib/rake/extensiontask.rb:150:in `block in define_compile_tasks'
/home/dkowis/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `eval'
/home/dkowis/.rvm/gems/ruby-2.0.0-p0/bin/ruby_noexec_wrapper:14:in `<main>'
Tasks: TOP => compile => compile:x86-mingw32 => compile:bool_ext:x86-mingw32 => copy:bool_ext:x86-mingw32:2.0.0 => tmp/x86-mingw32/bool_ext/2.0.0/bool_ext.so => tmp/x86-mingw32/bool_ext/2.0.0/Makefile
(See full trace by running task with --trace)
make: *** [winruby] Error 1
```

**Comment by dkowis** [comment]
Was trying to do #23, but i fail at things :(

**Comment by mattwynne** [comment]
WOMM (OS X)

Looks like it hasn't downloaded mingw or put it into your path properly maybe?

**Comment by aslakhellesoy** [comment]
@mattwynne you tried with `2.0.0-p0`?

**Comment by mattwynne** [comment]
On 4 Mar 2013, at 08:05, Aslak Hellesøy notifications@github.com wrote:

> @mattwynne you tried with 2.0.0-p0?
> 
> Yes, and it works fine for me.

➤ ruby -v
ruby 2.0.0p0 (2013-02-24 revision 39474) [x86_64-darwin12.2.0]

**Comment by aslakhellesoy** [comment]
I managed to hack around this:

``` ruby
module Win32
  module Resolv
    def get_hosts_path
      '/etc/hosts'
    end
    module_function :get_hosts_path
  end
end
```

This file needs to go into `ruby/tmp/x86-mingw32/bool_ext/2.0.0/win32/resolv.rb`. If we use this hack, it should be generated by the build script.

**Comment by aslakhellesoy** [comment]
It occasionally happens on travis as well. See build [5363278](https://travis-ci.org/cucumber/bool/jobs/5363278).

**Comment by aslakhellesoy** [comment]
@dkowis this should be fixed now. Can you try again?

**Comment by larskanis** [comment]
The root cause for this issue is in the platform faking mechanism of rake-compiler when used with `bundle exec`. I've proposed a patch for this: https://github.com/luislavena/rake-compiler/pull/83 . That should obsolete the monkey patch above.
